version: '3.8'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    platform: linux/arm64/v8
    container_name: homeassistant
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    network_mode: host

  nodered:
    image: nodered/node-red:latest
    platform: linux/arm64/v8
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped

  jarvis-python:
    build:
      context: ./homeassistant/scripts
      dockerfile: Dockerfile.pi
    platform: linux/arm64/v8
    container_name: jarvis-python
    volumes:
      - ./homeassistant/scripts:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
      - GOOGLE_OAUTH_TOKEN=${GOOGLE_OAUTH_TOKEN}
    restart: unless-stopped

  rhasspy:
    image: rhasspy/rhasspy:latest
    platform: linux/arm64/v8
    container_name: rhasspy
    volumes:
      - ./rhasspy:/profiles
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "12101:12101"
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
    ports:
      - "1883:1883"
    restart: unless-stopped
